### ISSUE TITLE
Windows build fails to run with Entry Point Not Found

### ISSUE THREAD

**Issue by brookst** [AllenDang/img_maniac#1]
The Windows build won't start on Windows 11 (10.0.22621 N/A Build 22621). An empty terminal opens and an error dialog box opens with the message:
> The procedure entry point
> _ZSt28__throw_bad_array_new_lengthv could not be located in
> the dynamic link library
> C:\\...\img_maniac_win_x64\img_maniac.exe

According to [this SO question](https://stackoverflow.com/questions/69773877/getting-throw-bad-array-new-lengthv-when-trying-to-use-stdvectorpush-back), it's a libstdc++ issue. Seems like the compiler trying to statically link it, but not actually emitting the symbol.

**Comment by brookst** [comment]
Just to note, building on windows natively seems to work so I guess this is a cross-compilation issue.

Maybe a CI system to build releases would be the easiest fix.

**Comment by cristian-tentella** [comment]
I'm experiencing the same exact issue (Windows 11 Pro 22621.1555)

**Comment by AllenDang** [comment]
Yes, I need to make a CI action to do the release.
