### ISSUE TITLE
relicense to MIT or Apache 2.0

### ISSUE THREAD

**Issue by adsick** [AllenDang/img_maniac#2]
Using this dual license is considered a best practice in Rust and Bevy ecosystem.

**Comment by AllenDang** [comment]
It is MIT.... Are you suggesting that it should support both MIT and Apache 2.0?

**Comment by AllenDang** [comment]
It's done.

**Comment by adsick** [comment]
Yes, I meant a dual license. Cargo.toml pacckage.license has to be updated as well.
