### ISSUE TITLE
Does not compile on Linux

### ISSUE THREAD

**Issue by adsick** [AllenDang/img_maniac#3]
There are problems in winit - to fix this we need to add "wayland" or "x11" feature in Cargo.toml.

**Comment by vitali2y** [comment]
On _Linux Mint_ (_X11_):
```
error: The platform you're compiling for is not supported by winit
  --> /home/vit/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.28.3/src/platform_impl/mod.rs:67:1
```

**Comment by AllenDang** [comment]
I reset to bevy's default features in Cargo.toml, might be easier to fix this and remain compilable on windows.

**Comment by vitali2y** [comment]
> On _Linux Mint_ (_X11_):

Successfully compiled and started the latest "_master_".
