### ISSUE TITLE
use 2d camera instead of 3d one

### ISSUE THREAD

**Issue by adsick** [AllenDang/img_maniac#4]
I'm not sure why this crate uses 3d camera, the content is all 2d. Camera 2d has `OrthographicProjection` component which has `scale`, it is what you want instead of adjusting `z` coordinate (unless you actually want images to float in 3d space)

useful: https://github.com/bevyengine/bevy/issues/2580

P.S. beware of this issue: https://github.com/bevyengine/bevy/issues/239

**Comment by AllenDang** [comment]
Will 2d has better performance?

**Comment by adsick** [comment]
It may not perform better, but it makes more sense, and (hopefully) is simpler to work with.

**Comment by piaoger** [comment]
> float in 3d space

I just tried modify the camera to iso view when I known it's 3d camera. Image can have different coordinates and it looks interesting .

**Comment by AllenDang** [comment]
for me, 3d is more familiar, :)

**Comment by AllenDang** [comment]
change to use ortho camera, the distortion should be fixed now.
