### ISSUE TITLE
Consider checking `Cargo.toml` back into git

### ISSUE THREAD

**Issue by expenses** [AllenDang/img_maniac#8]
Hi! https://github.com/AllenDang/img_maniac/pull/6 for rid of the `Cargo.lock` file. It's totally up to you, but I've found that having `Cargo.lock` committed for binary projects has been very useful for stability and debugging. It's recommended by the cargo guide as well: https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries. I'd consider checking it back into git. (@adsick).

**Comment by AllenDang** [comment]
@expenses Agreed, i will add it back

**Comment by AllenDang** [comment]
I got this comment, maybe Cargo.lock should be ignored?
# Remove Cargo.lock from gitignore if creating an executable, leave it for libraries
# More information here https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html
